### ISSUE TITLE
[Feature Request]: Unable to switch workflows on the browser, using shortcut keys, interface not controlled by mouse

### ISSUE THREAD

**Issue by yatoubusha** [Comfy-Org/ComfyUI_frontend#1694] opened 2024-11-26 06:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Unable to switch workflows on the browser, using shortcut keys, interface not controlled by mouse

### Proposed workflow

Unable to switch workflows on the browser, using shortcut keys, interface not controlled by mouse

### Additional information

Unable to switch workflows on the browser, using shortcut keys, interface not controlled by mouse

**Comment by LukeG89** [comment] 2024-11-26 10:01
@yatoubusha Make sure everything is up-to-date (ComfyUI and all custom nodes). 

If you still have the problem, try disabling your nodes with `--disable-all-custom-nodes` argument and see if the problem is gone.
There might be an extension that is causing the issue.

**Comment by huchenlei** [comment] 2024-11-26 15:03
Closing for insufficient information.

**Closed** 2024-11-26 15:03 UTC
Labels: enhancement
