### ISSUE TITLE
"Note" node is missing

### ISSUE THREAD

**Issue by Backroads4Me** [Comfy-Org/ComfyUI_frontend#288] opened 2024-08-04 00:58 UTC
On a Linux server with the new front end the "Note" node is no longer available.

**Comment by huchenlei** [comment] 2024-08-04 01:20
Closing for now as I cannot reproduce the issue. Please also check if primitive and reroute nodes are available in the search list, and attach full browser log. Ideally a short video would also be helpful for us to understand what is happening.

**Closed by huchenlei** 2024-08-04 01:20 UTC
Labels: bug, Not Reproducable
